// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddAddress struct {
	RollNo   int    `json:"roll_no"`
	City     string `json:"city"`
	District string `json:"district"`
	Pin      int    `json:"pin"`
	State    string `json:"state"`
}

type AddMarks struct {
	RollNo      int `json:"roll_no"`
	Physics     int `json:"physics"`
	Chemistry   int `json:"chemistry"`
	Mathematics int `json:"mathematics"`
}

type Address struct {
	Error    bool   `json:"error"`
	Message  string `json:"message"`
	RollNo   int    `json:"roll_no"`
	City     string `json:"city"`
	District string `json:"district"`
	Pin      int    `json:"pin"`
	State    string `json:"state"`
}

type DeleteStudent struct {
	RollNo int `json:"roll_no"`
}

type Join struct {
	Error       bool   `json:"error"`
	Message     string `json:"message"`
	RollNo      int    `json:"roll_no"`
	Name        string `json:"name"`
	Dept        string `json:"dept"`
	Email       string `json:"email"`
	City        string `json:"city"`
	District    string `json:"district"`
	Pin         int    `json:"pin"`
	State       string `json:"state"`
	Physics     int    `json:"physics"`
	Chemistry   int    `json:"chemistry"`
	Mathematics int    `json:"mathematics"`
}

type Marks struct {
	Error       bool   `json:"error"`
	Message     string `json:"message"`
	RollNo      int    `json:"roll_no"`
	Physics     int    `json:"physics"`
	Chemistry   int    `json:"chemistry"`
	Mathematics int    `json:"mathematics"`
}

type NewStudent struct {
	RollNo int    `json:"roll_no"`
	Name   string `json:"name"`
	Dept   string `json:"dept"`
	Year   int    `json:"year"`
	MobNo  int    `json:"mob_no"`
	Email  string `json:"email"`
	Dob    int    `json:"dob"`
}

type StudentInfo struct {
	Error   bool     `json:"error"`
	Message string   `json:"message"`
	RollNo  int      `json:"roll_no"`
	Name    string   `json:"name"`
	Dept    string   `json:"dept"`
	Year    int      `json:"year"`
	MobNo   int      `json:"mob_no"`
	Email   string   `json:"email"`
	Dob     int      `json:"dob"`
	Address *Address `json:"address"`
}

type UpdateStudent struct {
	RollNo int    `json:"roll_no"`
	Name   string `json:"name"`
	Dept   string `json:"dept"`
	Year   int    `json:"year"`
	MobNo  int    `json:"mob_no"`
	Email  string `json:"email"`
	Dob    int    `json:"dob"`
}
